;====================================================================
; Main.asm file generated by New Project wizard
;
; Created:   lun oct 28 2019
; Processor: ATmega328P
; Compiler:  AVRASM (Proteus)
;====================================================================

;====================================================================
; DEFINITIONS
;====================================================================

;====================================================================
; VARIABLES
;====================================================================

;====================================================================
; RESET and INTERRUPT VECTORS
;====================================================================

.include<m328pdef.inc>
.org 0x00

      ; Reset Vector
      
	rjmp  Start
      

;====================================================================
; CODE SEGMENT
;====================================================================

Start:
	
	ldi r16, 0xFF	;temp
	ldi r17, 0x00	;num1
	ldi r18, 0x01	;num2
	ldi r19, 10	;Límite
	
	out ddrb, r16
	out ddrd, r17
	
	mov r16, r17
	clc
      
Loop:
	
	in r20, pind	;Se lee el pin 7 del puerto d
	sbis pind, 7	;Si se lee tierra (cero) brinca a off, en caso contrario a on
	rjmp off
	rjmp on
	
on:
	out portb, r18
	
	brbs 0, Loop
	
	mov r16, r17
	mov r17, r18
	add r16, r17
	mov r18, r16
	mov r16, r17
	
	dec r19
	cpi r19, 0
	breq Start
	
	sec
	
	rjmp Loop
	
off: 
	out portb, r18
	clc
	rjmp Loop

;====================================================================
